name: Sync GitLab Submodule

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Update submodule
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git submodule update --remote devops/pipeline-CICD-2408-IB
          git add devops/pipeline-CICD-2408-IB
          git diff --staged --quiet || git commit -m "📦 Update GitLab submodule"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}